### PR TITLE
chore: moves `dog` to `DORMANT.md`

### PR DESCRIPTION
**Pull request by johnalanwoods**
removing dog as per #5.

@yozachar - would you mind reviewing?

### CODE REVIEW

**Comment by yozachar** [comment]
Hi @johnalanwoods, I think having a separate table like so, might be better:

```md
...

### Dormant

Tools that have seen a pause in developmental activities for over 3 years.

|     Name     | Description                                                 | Status                                       | Screenshot                                                        | Alternatives |
| :----------: | ----------------------------------------------------------- | -------------------------------------------- | :---------------------------------------------------------------- | ------------ |
| [`dog`][dog] | A user-friendly command-line DNS client. `dig` on steroids. | ![_][dog-ghst] ![_][dog-lang] ![_][dog-ghlc] | <img alt="dog-preview" width="300" src="./screenshots/dog.png" /> | `doggo`      |

<!--Links-->

...
```

**Comment by johnalanwoods** [comment]
I hear ya, my only concern is that the repo will end up cluttered rather than being a concise index. What ya think?

**Comment by johnalanwoods** [comment]
sounds great, any chance you have time to do that today? If not will get it done by Friday, snowed atm.

**Comment by yozachar** [comment]
Sorry, not today.

**Comment by yozachar** [comment]
@johnalanwoods, could you please review.

**Comment by johnalanwoods** [comment]
Looks great! - and sorry I didn't get to this myself last week, work was crazy busy.

**Pull request merged**
